### ISSUE TITLE
Build failing in Android: Task :app:checkDebugDuplicateClasses FAILED

### ISSUE THREAD

**Issue by ammaarkhan** [naveenvignesh5/rn-ocr-lib#3]
I am simply importing rn-ocr-lib in my App.tsx and then when I run: 'npx react-native run-android', I am getting error: 
'Task :app:checkDebugDuplicateClasses FAILED'. 

My build.gradle properties are:
```
ext {
      buildToolsVersion = "33.0.0"
      minSdkVersion = 21
      compileSdkVersion = 33
      targetSdkVersion = 33
      ndkVersion = "23.1.7779620"
}
```

**Comment by naveenvignesh5** [comment]
@ammaarkhan looking into it.

**Comment by ammaarkhan** [comment]
Hi @naveenvignesh5, I fixed it by adding this to the top of app/build.gradle file:

```
plugins {
    id "com.android.application"
    id 'com.google.gms.google-services'
    id "com.facebook.react"
    id 'org.jetbrains.kotlin.android' version '1.8.10'
}
```

**Comment by naveenvignesh5** [comment]
Noted @ammaarkhan. Closing this issue.
